apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fusiion-notification
  namespace: fusiion
  labels:
    app: fusiion
    name: fusiion-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fusiion
      name: fusiion-notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: fusiion
        name: fusiion-notification
    spec:
      containers:
      - name: fusiion-notification
        image: fusiion/sii-codelab-chaos-notification:latest
        imagePullPolicy: IfNotPresent
        env:  
          - name: SPRING_DATA_MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-password
          - name: SPRING_DATA_MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-username
          - name: SPRING_RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-password
          - name: SPRING_RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-username
        args: ["--server.port=8080"
                ,"--spring.data.mongodb.database=Notifications"
                ,"--spring.data.mongodb.uri=mongodb://mongo-0.mongo-service:27017/FUSIION_FUSIION-NOTIFICATION"
                ,"--spring.rabbitmq.host=rabbitmq-0.rabbitmq-service"
                ,"--spring.rabbitmq.port=5672"
                ]
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
