apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusiion-statistiques
  namespace: fusiion
  labels:
    app: fusiion
    name: fusiion-statistiques
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fusiion
      name: fusiion-statistiques
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: fusiion
        name: fusiion-statistiques
    spec:
      containers:
      - name: fusiion-statistiques
        image: fusiion/sii-codelab-chaos-statistiques:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SPRING_DATA_MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-password
          - name: SPRING_DATA_MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-username
          - name: SPRING_RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-password
          - name: SPRING_RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: rabbitmq-username
        args: ["--server.port=8080"
                ,"--spring.data.mongodb.database=Statistiques"
                ,"--spring.data.mongodb.uri=mongodb://mongo-0.mongo-service:27017/FUSIION_FUSIION-STATISTIQUES"
                ,"--spring.rabbitmq.host=rabbitmq-0.rabbitmq-service"
                ,"--spring.rabbitmq.port=5672"
                ]
        ports:
        - containerPort: 8080
      initContainers:
        - name: init
          image: busybox:1.28
          command: ["sh", "-c", "until (nslookup mongo-service && nslookup rabbitmq-service); do echo waiting; sleep 1; done;"]
      imagePullSecrets:
      - name: regcred
