# Spring properties
spring:
  application:
     name: fusiion-gestion-competences
  data:
    neo4j: 
      uri: bolt://192.168.99.100:17687
      username: neo4j
      password: password
     
server:
  port: 8081
  
spring.rabbitmq:
  host : 192.168.99.100
  port : 8088
  username : user
  password : password