apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-service
  namespace: fusiion
  labels:
    app: fusiion
    name: nginx-ingress-service
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: fusiion
    name: nginx-ingress
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment 
metadata:
  name: nginx-ingress
  namespace: fusiion
  labels:
    app: fusiion
    name: nginx-ingress
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fusiion
      name: nginx-ingress
  template:
    metadata:
      labels:
        app: fusiion
        name: nginx-ingress
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      containers:
      - image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
        name: nginx-ingress
        args:
            - /nginx-ingress-controller
            - --default-backend-service=$(POD_NAMESPACE)/fusiion-front-service
            - --configmap=$(POD_NAMESPACE)/nginx-configuration
            - --annotations-prefix=nginx.ingress.kubernetes.io
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
