version: '2'
networks:
  competence:
  collaborateur:
  statistiques:
  authentification:
  gaming:
  clients:
  notification:

services:
  competences:
    image: fusiion/sii-codelab-chaos-gestion-competences
    container_name: "fusiion-gestion-competences"
    environment:
     - SPRING_DATA_NEO4J_USERNAME=neo4j
     - SPRING_DATA_NEO4J_PASSWORD=password
     - SPRING_DATA_NEO4J_URI=bolt://neo4j
     - SPRING_RABBITMQ_HOST=rabbitmq
     - SPRING_RABBITMQ_PORT=5672
     - SPRING_RABBITMQ_USERNAME=user
     - SPRING_RABBITMQ_PASSWORD=password
    ports:
     - "8081:8081"
    depends_on:
     - neo4j
     - authentification
     - rabbitmq
    networks:
     - competence

  collaborateurs:
    image: fusiion/sii-codelab-chaos-gestion-collaborateurs
    container_name: "fusiion-gestion-collaborateurs"
    environment:
     - SPRING_DATA_MONGODB_DATABASE=Collaborateurs
     - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/FUSIION_FUSIION-GESTION-COLLABORATEURS
     - SPRING_DATA_MONGODB_USERNAME=user
     - SPRING_DATA_MONGODB_PASSWORD=password
     - SPRING_RABBITMQ_HOST=rabbitmq
     - SPRING_RABBITMQ_PORT=5672
     - SPRING_RABBITMQ_USERNAME=user
     - SPRING_RABBITMQ_PASSWORD=password
    ports:
     - "8083:8083"
    depends_on:
     - mongodb
     - authentification
     - rabbitmq
    networks:
     - collaborateur

  authentification:
    image: fusiion/sii-codelab-chaos-authentification:latest
    container_name: "fusiion-authentification"
    environment:
     - SPRING_DATA_MONGODB_DATABASE=Utilisateurs
     - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/FUSIION_FUSIION-AUTHENTIFICATION
     - SPRING_DATA_MONGODB_USERNAME=user
     - SPRING_DATA_MONGODB_PASSWORD=password
     - SII_FUSIION_URL=10.10.2.22/modifiermdp/
     - SPRING_RABBITMQ_HOST=rabbitmq
     - SPRING_RABBITMQ_PORT=5672
     - SPRING_RABBITMQ_USERNAME=user
     - SPRING_RABBITMQ_PASSWORD=password
    ports:
     - "8080:8080"
    depends_on:
     - mongodb
     - rabbitmq
    networks:
     - authentification

  clients:
    image: fusiion/sii-codelab-chaos-gestion-clients
    container_name: "fusiion-gestion-clients"
    environment:
     - SPRING_DATA_NEO4J_USERNAME=neo4j
     - SPRING_DATA_NEO4J_PASSWORD=password
     - SPRING_DATA_NEO4J_URI=bolt://neo4j
     - SPRING_RABBITMQ_HOST=rabbitmq
     - SPRING_RABBITMQ_PORT=5672
     - SPRING_RABBITMQ_USERNAME=user
     - SPRING_RABBITMQ_PASSWORD=password
    ports:
        - "8084:8084"
    depends_on:
        - neo4j
        - authentification
        - rabbitmq
    networks:
        - clients

  mongodb:
    extends:
      file: database.yml
      service: mongodb
    networks:
     - authentification
     - gaming
     - collaborateur
     - statistiques
     - notification

  neo4j:
    extends:
      file: database.yml
      service: neo4j
    networks:
     - competence
     - clients
     
  rabbitmq:
    extends:
      file: database.yml
      service: rabbitmq
    networks:
        - competence
        - gaming
        - authentification
        - collaborateur
        - clients
        - statistiques
        - notification
     
volumes:
  mongodb_data:
  neo4j_data:
  rabbitmq_data:
