apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: fusiion
  labels:
    app: fusiion
    name: mongo-service
spec:
  ports:
  - port: 27017
    name: mongo-port
    targetPort: 27017
  clusterIP: None
  selector:
    app: fusiion
    name: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: fusiion
  labels:
    app: fusiion
    name: mongo
spec:
  serviceName: mongo-service
  selector:
    matchLabels:
      app: fusiion
  template:
    metadata:
      labels:
        app: fusiion
        name: mongo
        component: primary
    spec:
       terminationGracePeriodSeconds: 10
       containers:
         - name: mongo
           image: fusiion/mongo:latest
           resources:
             limits:
               memory: 768Mi
               cpu: 1
             requests:
               memory: 256Mi
               cpu: 0.3 
           ports:
             - containerPort: 27017
           env:
             - name: MONGODB_USERNAME
               valueFrom:
                 secretKeyRef:
                   name: mongodb-secret
                   key: mongodb-username
             - name: MONGODB_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: mongodb-secret
                   key: mongodb-password
             - name: MONGODB_ROOT_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: mongodb-secret
                   key: mongodb-root-password
