apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  namespace: fusiion
  labels:
    app: fusiion 
    name: neo4j-service
    component: core
spec:
  clusterIP: None
  ports:
  - port: 7687
    targetPort: 7687
    name: bolt
  selector:
    app: fusiion
    name: neo4j-core
    component: core
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: neo4j-core
  namespace: fusiion
spec:
  serviceName: neo4j-service
  replicas: 1
  template:
    metadata:
      labels:
        app: fusiion
        name: neo4j-core
        component: core
    spec:
      containers:
       - name: neo4j
         image: fusiion/neo4j-kube:latest
         imagePullPolicy: "IfNotPresent"
         resources:
             limits:
               memory: 1Gi
               cpu: 1
             requests:
               memory: 256Mi
               cpu: 0.4
         env:
          - name: NEO4J_dbms_mode
            value: CORE
          - name: NUMBER_OF_CORES
            value: "1"
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef:
                name: neo4j-secret
                key: neo4j-password
          - name: AUTH_ENABLED
            value: "true"
          - name: NEO4J_causal__clustering_discovery__type
            value: DNS
          - name: NEO4J_causal__clustering_initial__discovery__members
            value: "neo4j-core-0.neo4j-service.fusiion.svc.cluster.local:5000"
         command:
          - "/bin/bash"
          - "-ecx"
          - |
            export NEO4J_dbms_connectors_default__advertised__address=$(hostname -f)
            export NEO4J_causal__clustering_discovery__advertised__address=$(hostname -f):5000
            export NEO4J_causal__clustering_transaction__advertised__address=$(hostname -f):6000
            export NEO4J_causal__clustering_raft__advertised__address=$(hostname -f):7000
            export NEO4J_AUTH="neo4j/${NEO4J_PASSWORD}"
            exec /docker-entrypoint.sh "neo4j"
         ports:
          - containerPort: 5000
            name: discovery
          - containerPort: 7000
            name: raft
          - containerPort: 6000
            name: tx
          - containerPort: 7474
            name: browser
          - containerPort: 7687
            name: bolt
          - containerPort: 6362
            name: backup
