apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: fusiion
  labels:
    app: fusiion
    name: rabbitmq-service
spec:
  ports:
  - port: 5672
    name: rabbitmq-port
    targetPort: 5672
  clusterIP: None
  selector:
    app: fusiion
    name: rabbitmq

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: fusiion
  labels:
    app: fusiion
    name: rabbitmq
spec:
  serviceName: rabbitmq-service
  selector:
    matchLabels:
      app: fusiion
  template:
    metadata:
      labels:
        app: fusiion
        name: rabbitmq
    spec:
      terminationGracePeriodSeconds: 10
      containers:
       - name: rabbitmq
         image: fusiion/rabbitmq:latest
         resources:
              limits:
                memory: 768Mi
                cpu: 1
              requests:
                memory: 256Mi
                cpu: 0.4
         imagePullPolicy: "IfNotPresent"
         env:
           - name: RABBITMQ_DEFAULT_PASS
             valueFrom:
               secretKeyRef:
                 name: rabbitmq-secret
                 key: rabbitmq-password
           - name: RABBITMQ_DEFAULT_USER
             valueFrom:
               secretKeyRef:
                 name: rabbitmq-secret
                 key: rabbitmq-username
         ports:
          - containerPort: 5672

