apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   namespace: fusiion
   name: openebs-mongodb
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "1"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 2G
  openebs.io/fstype: "xfs"
